language: go
go:
  - "1.10"
  - tip
env:
  - CODECOV_TOKEN=7d00059e-7c3b-4ab4-ba5e-9b3fc0494062
before_install:
  - cp .netrc ~
  - chmod 600 .netrc
  - go get -t -v ./...
script:
  - go build && gofmt -d . && go test -race -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
