language: go
go:
  - "1.10"
before_install:
  - cp .netrc ~
  - chmod 600 .netrc
  - go get -v ./...
  - go get -tags=unit ./...
  - go get -u golang.org/x/lint/golint
script:
  - set -e
  - go build
  - if [[ -n "$(gofmt -l .)" ]]; then
      gofmt -d .;
      exit 1;
    fi
  - golint -set_exit_status .
  - go test -failfast -tags=unit -race -coverprofile=coverage.txt -covermode=atomic .
  - set +e
after_success:
  - bash <(curl -s https://codecov.io/bash)
