language: go
go:
  - "1.10"
before_install:
  - cp .netrc ~
  - chmod 600 .netrc
script:
  - go build
  - if [ -n "$(gofmt -l .)" ]; then
      echo "Code is not formatted correctly:"
      gofmt -d .
      exit 1
    fi
  - go test ./...
